// Afghanistan provinces with value/label keys
const provinces = [
  { value: "badakhshan", label: "Badakhshan" },
  { value: "badghis", label: "Badghis" },
  { value: "baghlan", label: "Baghlan" },
  { value: "balkh", label: "Balkh" },
  { value: "bamyan", label: "Bamyan" },
  { value: "daykundi", label: "Daykundi" },
  { value: "farah", label: "Farah" },
  { value: "faryab", label: "Faryab" },
  { value: "ghazni", label: "Ghazni" },
  { value: "ghor", label: "Ghor" },
  { value: "helmand", label: "Helmand" },
  { value: "herat", label: "Herat" },
  { value: "jowzjan", label: "Jowzjan" },
  { value: "kabul", label: "Kabul" },
  { value: "kandahar", label: "Kandahar" },
  { value: "kapisa", label: "Kapisa" },
  { value: "khost", label: "Khost" },
  { value: "kunar", label: "Kunar" },
  { value: "kunduz", label: "Kunduz" },
  { value: "laghman", label: "Laghman" },
  { value: "logar", label: "Logar" },
  { value: "nangarhar", label: "Nangarhar" },
  { value: "nimroz", label: "Nimroz" },
  { value: "nuristan", label: "Nuristan" },
  { value: "paktia", label: "Paktia" },
  { value: "paktika", label: "Paktika" },
  { value: "panjshir", label: "Panjshir" },
  { value: "parwan", label: "Parwan" },
  { value: "samangan", label: "Samangan" },
  { value: "sar-e-pol", label: "Sar-e Pol" },
  { value: "takhar", label: "Takhar" },
  { value: "urozgan", label: "Urozgan" },
  { value: "wardak", label: "Wardak" },
  { value: "zabul", label: "Zabul" }
]

export default provinces
